stages:
  - build_package

workflow:
  rules:
    - if: "$CI_COMMIT_TAG =~ /v.*/"

build:
  stage: build_package
  image: python:3.8
  script:
    - pip install poetry
    - poetry build
    - poetry config repositories.gitlab https://react-gitlab.space.noa.gr/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish -r gitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  only:
    - tags
