# Upload package to pypi everytime a release is created
name: Upload release to PyPI

# on:
#   release:
#     types: [created]
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Build and publish
        env:
          TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish -u __token__ -p $TOKEN
